name: Continous integration
on: [push, pull_request]
jobs:
  cs:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phpcs
      - name: Test code style
        run: phpcs
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4']
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl
          coverage: pcov
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: Test code style
        run: composer lint
      - name: Run tests
        run: composer test -- --coverage-clover coverage.xml --coverage-text
      - name: Get Ocular
        run: wget https://scrutinizer-ci.com/ocular.phar
      - name: Push code coverage
        run: php ocular.phar code-coverage:upload --format=php-clover coverage.xml
  release:
    name: Automated release
    needs: [test, cs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install dependencies for semantic-release
        run: npm ci
      - run: $(npm bin)/semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}